spring.application.name=scdf-source

# Bind the output of the Supplier bean to a RabbitMQ topic
spring.cloud.stream.bindings.timeSupplier-out-0.destination=time-topic

# RabbitMQ-specific producer settings
spring.cloud.stream.rabbit.bindings.timeSupplier-out-0.producer.routing-key-expression='time.key'